parameters:
- name: directory
  type: string

steps:
- task: CmdLine@2
  displayName: Run Checkov
  inputs:
    script: |
      pip install checkov
      checkov --directory $(directory) --output junitxml --soft-fail > $(System.DefaultWorkingDirectory)/checkov/checkreport.xml
# Publish Test Results v2
# Publish test results to Azure Pipelines.
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' # 'JUnit' | 'NUnit' | 'VSTest' | 'XUnit' | 'CTest'. Alias: testRunner. Required. Test result format. Default: JUnit.
    testResultsFiles: 'checkreport.xml' # string. Required. Test results files. Default: **/TEST-*.xml.
    searchFolder: '$(System.DefaultWorkingDirectory)/checkov' # string. Search folder. Default: $(System.DefaultWorkingDirectory).
    #mergeTestResults: false # boolean. Merge test results. Default: false.
    failTaskOnFailedTests: true # boolean. Fail if there are test failures. Default: false.
    testRunTitle: 'Checkov Results' # string. Test run title. 
  # Advanced
    #buildPlatform: # string. Alias: platform. Build Platform. 
    #buildConfiguration: # string. Alias: configuration. Build Configuration. 
    #publishRunAttachments: true # boolean. Upload test results files. Default: true.
  continueOnError: false
